export { default } from './GlobalStyles/GlobalStyles.js';
export { default as Icon } from './Icon/Icon';
export { default as Search } from './Search/Search';
export { default as Button } from './Button/Button';
export { default as InfoUser } from './InfoUser/InfoUser';
export { default as BoxInfo } from './BoxInfo/BoxInfo';
export { default as BoxItem } from './BoxItem/BoxItem';
export { default as ContainerElement } from './ContainerElement/ContainerElement';
export { default as Title } from './Title/Title';
export { default as HeroItem } from './HeroItem/HeroItem';
export { default as TitlePage } from './TitlePage/TitlePage';
export { default as ImageHalf } from './ImageHalf/ImageHalf';
export { default as BoxReview } from './BoxReview/BoxReview';
export { default as PlacedOrder } from './PlacedOrder/PlacedOrder';
export { default as InfoProfile } from './InfoProfile/InfoProfile';
export { default as TotalItem } from './TotalItem/TotalItem';
export { default as Input } from './Input/Input';
